export const lawsActionsTypes = {
    START_GET_LAWS : "START_GET_LAWS",
    GET_LAWS_SUCCESSFULLY : "GET_LAWS_SUCCESSFULLY",
    ERROR_GETTING_LAWS : "ERROR_GETTING_LAWS",
    SET_CATEGORY:"SET_CATEGORY"
}